### PR TITLE
fix double free error in requirements

### PR DESCRIPTION
**Pull request by eagmon**
check if my local requirements can save the GitHub action from double free error.

### CODE REVIEW

**Comment by eagmon** [comment]
@jonrkarr -- I'm pretty sure there is a double free error coming from one or more of the most recently released biosimulators libraries. This is not coming from python. In this PR I reverted the pytest action to install previous versions listed in requirements.txt that I'm using on my computer, and it passes. The Docker test is failing with the latest Biosimulators Docker image. Previously (and on master) the pytest was also failing when it installed the most recent biosimulators versions.

**Comment by jonrkarr** [comment]
This may be fixed by a few things
- Uses tellurium 2.2.0 rather than the new version released two days ago. I wasn't aware of this and haven't verified it. I believe this version changes the required version of numpy, which may be the source of the problem.
- Reinstall numpy and matplotlib after all other packages have been installed.

More discussion of known issues in combining multiple simulation tools into 1 Python environment is here: https://github.com/biosimulators/Biosimulators/#utilizing-multiple-simulation-tools-within-a-single-python-environment

**Comment by jonrkarr** [comment]
The double free issue is definitely coming from the new version of libRoadRunner (underlying simulation tool for tellurium). Upgrading it in the Docker image for 2.2.0 leads to double free errors.

I recommend sticking with tellurium 2.2.0 for now.

I'm pretty sure this has to be fixed on the Road Runner side. It sounds like some aspect of the compiled library is corrupt. I'll try to distill this down for them.

**Comment by jonrkarr** [comment]
biosimulators-tellurium 0.1.23 adds a requirement for tellurium < 2.2.0 and rrplugins < 2.0.5. 

`ghcr.io/biosimulators/biosimulators:0.0.8` should be published shortly with biosimulators-tellurium 0.1.23.

**Pull request closed without merging**
