### PR TITLE
Fba update

### PR DESCRIPTION
**Pull request by eagmon**
more changes toward getting the ODE_FBA composite working.

### CODE REVIEW

**Comment by eagmon** [comment]
@jonrkarr -- I got fba to successfully update targets! The next error comes in `biosimulators_tellurium.core.preprocess_sed_task`. This calls `get_model_change_target_tellurium_change_map`:

**Comment by eagmon** [comment]
This might not be sufficient:

**Comment by jonrkarr** [comment]
I think issue is that these are instances of SBML `LocalParameter` (parameters nested within rate laws for specific reactions), and tellurium doesn't expose the ability to change the local parameters. I don't see why other simulation tools would have a similar limitation. I'll have to add an option to filter these out from the list of possible inputs.

**Comment by jonrkarr** [comment]
Different simulators expose different capabilities, which largely aren't documented. Unfortunately, we're going to have to discover them by trial and error.

There are some clues in http://sbml.org/Facilities/Database. But, there's a variety of limitations. It only includes a few tools, this tests SBML feature support, not the ability to programmatically make changes through APIs, most of the information is old, etc.

**Comment by jonrkarr** [comment]
I'll push a change in a minute. By default, local parameters won't be included. No need to change your code.

You

**Comment by jonrkarr** [comment]
This should be released to PyPI in a few minutes. It might be easier to work from the version in GitHub.

**Comment by eagmon** [comment]
That seems to have worked. Next error:
```
  File "/Users/eranagmon/code/vivarium-biosimulators/vivarium_biosimulators/processes/biosimulator_process.py", line 315, in run_task
    raw_results, log = self.exec_sed_task(
  File "/Users/eranagmon/.pyenv/versions/v-tellurium/lib/python3.9/site-packages/biosimulators_tellurium/core.py", line 241, in exec_sed_task
    road_runner.model[component_id] = new_value
  File "/Users/eranagmon/.pyenv/versions/v-tellurium/lib/python3.9/site-packages/roadrunner/roadrunner.py", line 2402, in __setitem__
    return _roadrunner.ExecutableModel___setitem__(self, id, value)
RuntimeError: could not set value for MgADP, it is defined by an assignment rule, can not be set independently., at int rrllvm::LLVMExecutableModel::setValues(bool (*)(rrllvm::LLVMModelData *, int, double), GetNameFuncPtr, size_t, const int *, const double *)
Uncaught exception. Entering post mortem debugging
```

**Comment by jonrkarr** [comment]
I'll filter this out too. This is another trivial change. I'll take care of this around 9pm.

This a parameter or variable set via an instance of SBML `AssignmentRule` or `InitialAssignment`. Such variables/parameters have an associated value/initial conditions stored in SBML files. However, these values basically are irrelevant because the values are controlled by algebraic expressions derived from the values of other parameters and/or variables. Changes at the XML level are possible, although meaningless. Simulation tools seem to handle such parameters/variables differently.

**Pull request merged**
